import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "AI Procurement OS",
    template: "%s · AI Procurement OS",
  },
  description:
    "South African tender compliance and bid preparation intelligence. Digital twin ingestion, compliance gap analysis, BOQ pricing and human-approved submission packs.",
};

/*
 * `LayoutProps<"/">` is generated by `next typegen` (Next 16). It types `children`
 * and any route params for this segment — do not hand-roll the prop type.
 */
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en-ZA" className="h-full antialiased">
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
