import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "AI Procurement OS",
    template: "%s · AI Procurement OS",
  },
  description:
    "Tender compliance checker for South African bidders. Reads tenders and company documents, flags expired documents and stale certified copies, and lists every compliance gap.",
};

export const viewport: Viewport = {
  // Matches --color-canvas in globals.css.
  themeColor: "#f6f6f4",
};

/*
 * `LayoutProps<"/">` is generated by `next typegen` (Next 16). It types `children`
 * and any route params for this segment — do not hand-roll the prop type.
 */
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en-ZA" className="h-full antialiased">
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
